select etat, placa_pod+coalesce(placa_dod,0) as miesieczne_zarobki
from PRACOWNICY;

select nazwisko, id_zesp, placa_pod
from pracownicy
where placa_pod between 300 and 800;

select nazwisko, etat, id_zesp
from pracownicy
where nazwisko like '%SKI';

select * from pracownicy
where placa_pod>1000 and id_szefa is not null;

select nazwisko, id_zesp
from pracownicy
where id_zesp=20 and (nazwisko like 'M%' or nazwisko like '%SKI');

select nazwisko, etat, placa_pod/160
from pracownicy
where etat not in ('ASYSTENT','STAŻYSTA','ADIUNKT')
and placa_pod not between 400 and 800
order by placa_pod;

select nazwisko || ' PRACUJE OD ' || ZATRUDNIONY || ' I ZARABIA ' || PLACA_POD AS PROFESOROWIE
FROM PRACOWNICY
WHERE ETAT='PROFESOR';

select nazwisko, substr(etat,1,2) || id_prac as kod
from praCOWNICY;

SELECT NAZWISKO, TRANSLATE(NAZWISKO,'KLM','XXX') AS WOJNA
FROM PRACOWNICY;

SELECT NAZWISKO
FROM PRACOWNICY
WHERE INSTR(NAZWISKO,'L',1,1)>0
AND INSTR(NAZWISKO,'L',1,1)<LENGTH(NAZWISKO)/2;

SELECT NAZWISKO, ROUND(PLACA_POD*1.15) AS PODWYZKA
FROM PRACOWNICY;

SELECT NAZWISKO, ZATRUDNIONY, 
SUBSTR((DATE '2000-01-01' - ZATRUDNIONY) year(2) TO MONTH,2,2) AS STAZ
FROM PRACOWNICY;

select NAZWISKO, TO_CHAR(ZATRUDNIONY,'MONTH, DD YYYY') AS DATA_ZATR
FROM PRACOWNICY;

SELECT TO_CHAR(CURRENT_DATE,'FMDAY')
FROM DUAL;

SELECT NAZWA, ADRES,
CASE
    WHEN ADRES LIKE 'P%' THEN 'NOWE MIASTO'
    WHEN ADRES LIKE 'M%' OR ADRES LIKE 'S%' THEN 'STARE MIASTO'
    WHEN ADRES LIKE 'W%' THEN 'GRUNWALD'
END AS DZIELNICA
FROM ZESPOLY;

SELECT NAZWISKO, PLACA_POD,
CASE
    WHEN PLACA_POD > 480 THEN 'POWYZEJ 480'
    WHEN PLACA_POD < 480 THEN 'PONIZEJ 480'
    ELSE 'DOKLADNIE 480'
END AS PROG
FROM PRACOWNICY;

SELECT MIN(PLACA_POD), MAX(PLACA_POD), MAX(PLACA_POD)-MIN(PLACA_POD) AS ROZNICA
FROM PRACOWNICY;

SELECT ETAT, AVG(PLACA_POD)
FROM PRACOWNICY
GROUP BY ETAT
ORDER BY AVG(PLACA_POD) DESC;

SELECT COUNT(*) AS PROFESORY
FROM PRACOWNICY
GROUP BY ETAT
HAVING ETAT='PROFESOR';

SELECT MAX(SUM(PLACA_POD+COALESCE(PLACA_DOD,0)))
FROM PRACOWNICY
GROUP BY ID_ZESP;

SELECT ID_SZEFA, MIN(PLACA_POD)
FROM PRACOWNICY
GROUP BY ID_SZEFA
ORDER BY MIN(PLACA_POD) DESC;

SELECT ID_ZESP, COUNT(*) AS ILU
FROM PRACOWNICY
GROUP BY ID_ZESP
HAVING  COUNT(*)>3
ORDER BY COUNT(*) DESC;

SELECT ID_PRAC, COUNT(*)
FROM PRACOWNICY
GROUP BY ID_PRAC
HAVING COUNT(*)>1;

SELECT ETAT, AVG(PLACA_POD), COUNT(*)
FROM PRACOWNICY
WHERE ZATRUDNIONY < DATE '1991-01-01'
GROUP BY ETAT;

SELECT ID_ZESP, ETAT, ROUND(AVG(PLACA_POD)), ROUND(MAX(PLACA_POD))
FROM PRACOWNICY
WHERE ETAT IN ('ASYSTENT','PROFESOR')
GROUP BY ID_ZESP, ETAT
ORDER BY ID_ZESP,ETAT;

SELECT EXTRACT(YEAR FROM ZATRUDNIONY) AS ROK, COUNT(*)
FROM PRACOWNICY
GROUP BY EXTRACT(YEAR FROM ZATRUDNIONY)
ORDER BY ROK;

SELECT LENGTH(NAZWISKO) AS ILE_LITER, COUNT(*)
FROM PRACOWNICY
GROUP BY LENGTH(NAZWISKO)
ORDER BY ILE_LITER;

SELECT 
COUNT(
CASE
    WHEN INSTR(UPPER(NAZWISKO),'A',1,1)>0 THEN 1
    ELSE NULL
END) AS NAZWISKA_Z_A,
COUNT(
CASE
    WHEN INSTR(UPPER(NAZWISKO),'E',1,1)>0 THEN 1
    ELSE NULL
END) AS NAZWISKA_Z_E
FROM PRACOWNICY;

SELECT NAZWISKO, ADRES, NAZWA
FROM PRACOWNICY JOIN ZESPOLY USING(ID_ZESP)
WHERE PLACA_POD>400
ORDER BY NAZWISKO;

SELECT NAZWISKO, placa_POD, ETAT, E.NAZWA as KAT_PLAC, Z.NAZWA
FROM PRACOWNICY P, ETATY E, ZESPOLY Z
WHERE PLACA_POD BETWEEN PLACA_MIN AND PLACA_MAX
AND P.ID_ZESP=Z.ID_ZESP;

SELECT NAZWISKO, ETAT, PLACA_POD*12 AS ROCZNA_PLACA, Z.NAZWA, E.NAZWA AS KAT_PLAC
FROM PRACOWNICY P, ETATY E, ZESPOLY Z
WHERE PLACA_POD BETWEEN PLACA_MIN AND PLACA_MAX
AND P.ID_ZESP=Z.ID_ZESP
AND PLACA_POD*12>5500
AND ETAT IN ('ASYSTENT','ADIUNKT');

SELECT P2.NAZWISKO AS PRACOWNIK, P2.ID_PRAC, P1.NAZWISKO AS SZEF, P2.ID_SZEFA
FROM PRACOWNICY P1 RIGHT JOIN PRACOWNICY P2 ON P1.ID_PRAC=P2.ID_SZEFA
ORDER BY P2.NAZWISKO;

SELECT NAZWA, COUNT(ID_PRAC), AVG(PLACA_POD) AS PLACA
FROM PRACOWNICY RIGHT JOIN ZESPOLY USING(ID_ZESP)
GROUP BY NAZWA;

SELECT P1.NAZWISKO, COUNT(*)
FROM PRACOWNICY P1 JOIN PRACOWNICY P2 ON P1.ID_PRAC=P2.ID_SZEFA
GROUP BY P1.NAZWISKO;

SELECT P2.NAZWISKO AS PRACOWNIK, P2.ZATRUDNIONY, P1.NAZWISKO AS SZEF, P1.ZATRUDNIONY,
SUBSTR((P2.ZATRUDNIONY - P1.ZATRUDNIONY) YEAR(2) TO MONTH,2,2)
FROM PRACOWNICY P1 JOIN PRACOWNICY P2 ON P1.ID_PRAC=P2.ID_SZEFA
WHERE P2.ZATRUDNIONY > P1.ZATRUDNIONY
AND SUBSTR((P2.ZATRUDNIONY - P1.ZATRUDNIONY) YEAR(2) TO MONTH,2,2) <= 10;

select etat
from pracownicy
where extract(year from zatrudniony)=1992
intersect
select etat
from pracownicy
where extract(year from zatrudniony)=1993;

select nazwisko, placa_pod, 'Poniżej 480' as prog
from pracownicy
where placa_pod<480
union
select nazwisko, placa_pod, 'Dokładnie 480' as prog
from pracownicy
where placa_pod=480
union
select nazwisko, placa_pod, 'Powyżej 480' as prog
from pracownicy
where placa_pod>480;